apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: teams-api
  description: Teams
spec:
  type: openapi
  lifecycle: production
  owner: peter
  system: teams
  definition: |
    openapi: 3.0.1
    info:
      title: Teams API
      version: '0.0'
    servers:
    - url: "/teams"
    
