apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: platform
  description: A collection of all Backstage example resources
spec:
  targets:
    - ./iam/catalog-info.yaml   
    - ./teams/catalog-info.yaml
