apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: platform
  description: A collection of all Backstage example resources
spec:
  targets:
    - ./iam/location.yaml
    - ./teams/location.yaml
