apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-testing
  annotations:
    github.com/project-slug: PeterGerrard/backstage-testing
spec:
  type: other
  lifecycle: unknown
  owner: peter
